#ifndef REASSETEXPLORER_GAMEBINDS_H
#define REASSETEXPLORER_GAMEBINDS_H
#include <cstdint>

enum GameBind : uint8_t {
    BIND_SCENE,
    BIND_GBUFFER_TYPE,
    BIND_CHECKERBOARD,
    BIND_ROOT_CONST,
    BIND_INSTANCE,
    BIND_REDIRECT,
    BIND_BINDLESS_DATA,
    BIND_TABLE,
    BIND_ZERO_CBV,
    BIND_ZERO_SRV,
    BIND_LIGHT_INFO,
    BIND_LIGHT_PARAMS,
    BIND_LIGHT_LIST,
    BIND_SCRATCH_UAV,
    BIND_SKINNING,
    BIND_TONEMAP,
    BIND_WHITE_POINT,
    BIND_ENVIRONMENT,
    BIND_SHADOW_CAST,
    BIND_SHADOW_ROTATION
};

#endif
