<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\REAssetExplorer.Core\REAssetExplorer.Core.csproj" />
    <ProjectReference Include="..\REAssetExplorer.Rendering\REAssetExplorer.Rendering.csproj" />
  </ItemGroup>

</Project>
